// Shared product data — used by main page and product SEO pages

export const BRANDS = [
  {
    name: 'WOTOFO', color: '#00E5FF',
    products: [
      { name: 'Wotofo nexPOD Stick — Starter Kit',          badge: 'STARTER KIT', badgeColor: '#BF00FF', puffs: '3,500 puffs',      price: '$9.99',  specs: '5.5ml · Mesh coil · Rechargeable · USB-C',                                                        nicotine: '20mg/ml',                      note: 'Includes battery + pod',                                                   flavours: ['Banana','Sour Lemon','Sour Raspberry','Tropical','Peach','Kiwifruit Pineapple','Blue Razz Ice','Cool Mint','Cola Ice','Golden Tobacco','Grape Ice','Kiwi Guava Passionfruit','Menthol Ice','Orange Soda','Peach Blueberry Ice','Peach Lemonade','Sour Apple','Strawberry Mango','Watermelon Ice'] },
      { name: 'Wotofo nexPOD Stick — Replacement Pods',     badge: 'POD',         badgeColor: '#BF00FF', puffs: '3,500 puffs',      price: '$9.99',  specs: '5.5ml · Fits nexPOD Stick battery kit',                                                           nicotine: '20mg/ml',                      note: 'Pod only — battery sold separately',                                       flavours: ['Banana','Sour Lemon','Sour Raspberry','Tropical','Peach','Kiwifruit Pineapple','Blue Razz Ice','Cool Mint','Cola Ice','Golden Tobacco','Grape Ice','Kiwi Guava Passionfruit','Menthol Ice','Orange Soda','Peach Blueberry Ice','Peach Lemonade','Sour Apple','Strawberry Mango','Watermelon Ice'] },
      { name: 'Wotofo nexPOD Stick — Battery Kit',          badge: 'DEVICE',      badgeColor: '#6b6b90', puffs: 'Device only',      price: '$10.00', specs: 'Rechargeable battery · USB-C',                                                                     nicotine: 'Pods sold separately',         note: 'Device only — pods sold separately',                                       flavours: [] },
      { name: 'Wotofo Nexpod 25K — Prefilled Starter Kit',  badge: 'STARTER KIT', badgeColor: '#00E5FF', puffs: '25,000 puffs',     price: '$30.00', specs: '18.5ml · 0.5Ω dual mesh · 1000mAh · USB-C · LED screen · Dual modes · Child lock',                nicotine: '26mg/ml',                      note: 'Includes battery + pod',                                                   flavours: ['Pineapple Coconut','Sour Lemon','Sweet Cream','Peach Apple','Blackberry Pomegranate','Strawberry Lemon','Lychee Passionfruit','Blueberry Watermelon'] },
      { name: 'Wotofo Nexpod 25K — Replacement Pods 26mg',  badge: 'POD',         badgeColor: '#00E5FF', puffs: '25,000 puffs',     price: '$20.00', specs: '18.5ml · 0.5Ω dual mesh · Fits Nexpod 25K device',                                               nicotine: '26mg/ml',                      note: 'Pod only — requires Nexpod 25K battery device',                            flavours: ['Pineapple Coconut','Sour Lemon','Sweet Cream','Peach Apple','Blackberry Pomegranate','Strawberry Lemon','Lychee Passionfruit','Blueberry Watermelon'] },
    ],
  },
  {
    name: 'INMOOD', color: '#00E5FF',
    products: [
      { name: 'Inmood Switch 2 — Replacement Pods 30K',    badge: 'POD',         badgeColor: '#00E5FF', puffs: '30,000 puffs',     price: '$25.00', specs: 'Next-gen Switch 2 pod · 30,000 puffs · USB-C · Requires Switch 2 Battery Kit',                  nicotine: '20mg/mL',                      note: 'Compatible with Switch 2 Battery Kit only',                                flavours: [] },
      { name: 'Inmood Switch 2 — Battery Kit',             badge: 'DEVICE',      badgeColor: '#6b6b90', puffs: 'Device only',      price: '$15.00', specs: 'Switch 2 battery · USB-C · Compatible with Switch 2 pods only',                                    nicotine: 'Pods sold separately',         note: 'Next generation Switch 2 device',                                          flavours: [] },
      { name: 'Inmood Switch — Replacement Pod 26mg',       badge: 'POD',         badgeColor: '#00E5FF', puffs: '5,000 puffs',      price: '$15.00', specs: '10ml · 1.0Ω mesh coil · Fits all Switch battery kits',                                          nicotine: '26mg/ml (High Strength)',      note: 'All flavours have an icy finish',                                          flavours: ['Banana (Ice)','Berry Lemon','Blackberry','Blueberry (Ice)','Blueberry Cherry','Blueberry Lemon','Blueberry Raspberry','Cherry Pomegranate','Grape','Grape Berry','Guava Passionfruit','Kiwifruit Pineapple (Ice)','Lemon Mint','Lychee (Ice)','Mango Peach (Ice)','Menthol (Ice)','Mint','Peach','Peach Blueberry','Peach Lemon','Peach Pineapple','Pineapple (Ice)','Pineapple Passionfruit','Raspberry Grape','Sour Apple','Strawberry','Strawberry Banana','Strawberry Blueberry','Strawberry Kiwifruit','Sweet Berry','Tea (Ice)','Tobacco','Vanilla Spice','Watermelon','Banana Custard','Strawberry Custard','Peach Blueberry Custard','Coffee'] },
      { name: 'Inmood Switch — Replacement Pod 16mg',       badge: 'POD',         badgeColor: '#00E5FF', puffs: '5,000 puffs',      price: '$15.00', specs: '10ml · 1.0Ω mesh coil · Fits all Switch battery kits',                                          nicotine: '16mg/ml (Low Strength)',       note: '',                                                                         flavours: ['Peach Blueberry','Blueberry','Watermelon','Vanilla Spice','Sour Apple','Pineapple','Peach Pineapple','Grape Berry','Guava Passionfruit','Mango Peach','Berry Lemon','Mint','Strawberry Kiwifruit','Strawberry Banana','Kiwifruit Pineapple'] },
      { name: 'Inmood Switch — Replacement Pod 0% Nicotine',badge: 'POD',         badgeColor: '#22c55e', puffs: '5,000 puffs',      price: '$15.00', specs: '10ml · 1.0Ω mesh coil · Fits all Switch battery kits',                                          nicotine: '0% — Zero Nicotine',           note: 'Nicotine-free option',                                                     flavours: ['Blueberry','Blueberry Raspberry','Cherry Pomegranate','Mango Peach','Mint','Pineapple','Sour Apple','Sweet Berry','Vanilla Spice'] },
      { name: 'Inmood Switch — Twin Pack (2 Pods) 26mg',    badge: 'TWIN PACK',   badgeColor: '#f59e0b', puffs: '5,000 puffs × 2', price: '$25.00', specs: '2 × pre-filled replacement pods · 26mg/ml',                                                       nicotine: '26mg/ml',                      note: 'Value pack — 2 pods included · Battery sold separately',                   flavours: ['Sour Lemon','Watermelon Passionfruit','Pineapple Coconut','Strawberry Watermelon','Strawberry Mango'] },
      { name: 'Inmood Switch — Starter Kit',                badge: 'STARTER KIT', badgeColor: '#00E5FF', puffs: '5,000 puffs',      price: '$20.00', specs: '550mAh removable battery · USB-C · 1.0Ω mesh coil · Adjustable airflow · Child lock',            nicotine: '26mg/ml or 16mg/ml',           note: 'Includes battery device + 1 pre-filled pod',                               flavours: [] },
      { name: 'Inmood Switch+ — Battery Kit (Upgraded)',    badge: 'DEVICE',      badgeColor: '#6b6b90', puffs: 'Device only',      price: '$10.00', specs: '650mAh (upgraded) · USB-C · Adjustable airflow · Child lock',                                     nicotine: 'Pods sold separately',         note: 'On/Off: tap USB port 5 times · Compatible with all Switch pods',           flavours: [] },
      { name: 'Inmood Prism — Starter Kit',                 badge: 'STARTER KIT', badgeColor: '#BF00FF', puffs: '15,000 puffs',     price: '$30.00', specs: '1300mAh removable battery · 16ml · Dual mesh coils · USB-C · LED screen · Child lock',           nicotine: '20mg/mL',                      note: 'Includes battery + pod',                                                   flavours: ['Cherry Blueberry','Strawberry Blueberry','Vanilla Spice','Sour Apple','Pineapple Coconut','Blackberry Cherry','Blueberry Raspberry','Raspberry Orange','Lemon Pineapple','Mango Grape','Watermelon Lychee','Strawberry Watermelon','Tropical Watermelon','Cherry Pomegranate','Watermelon Passionfruit','Strawberry Mango'] },
      { name: 'Inmood Prism — Replacement Pods 15K',        badge: 'POD',         badgeColor: '#BF00FF', puffs: '15,000 puffs',     price: '$20.00', specs: '16ml · Dual mesh coils · Requires Prism Battery Kit',                                            nicotine: '20mg/mL',                      note: 'Requires Inmood Prism Battery Kit (sold separately)',                      flavours: ['Cherry Blueberry','Strawberry Blueberry','Vanilla Spice','Sour Apple','Pineapple Coconut','Blackberry Cherry','Blueberry Raspberry','Raspberry Orange','Lemon Pineapple','Mango Grape','Watermelon Lychee','Strawberry Watermelon','Tropical Watermelon','Cherry Pomegranate','Watermelon Passionfruit','Strawberry Mango','Mint','Strawberry Kiwifruit','Sweet Grape','Peach Pineapple'] },
      { name: 'Inmood Prism — Replacement Pods 15K (28mg)', badge: 'POD',         badgeColor: '#BF00FF', puffs: '15,000 puffs',     price: '$20.00', specs: '16ml · Dual mesh coils · Requires Prism Battery Kit',                                            nicotine: '28mg/mL (High Strength)',      note: 'Requires Inmood Prism Battery Kit (sold separately)',                      flavours: ['Sweet Grape','Mint','Strawberry Mango','Strawberry Watermelon','Cherry Pomegranate','Watermelon Passionfruit','Tropical Watermelon','Peach Pineapple','Strawberry Kiwifruit'] },
      { name: 'Inmood Prism 20K — Replacement Pods (Clear)',badge: 'POD',         badgeColor: '#BF00FF', puffs: '20,000 puffs',     price: '$20.00', specs: 'Clear transparent pod · 18.5ml',                                                                  nicotine: '10mg or 28mg',                 note: 'Requires Inmood Prism Battery Kit (sold separately)',                      flavours: ['Blueberry','Grape Berry','Mint','Passionfruit Pineapple','Peach Blueberry','Pineapple','Pineapple Lemon','Pomegranate Kiwifruit','Sour Lemon','Strawberry Banana','Vanilla Spice'] },
      { name: 'Inmood Prism — Battery Kit',                 badge: 'DEVICE',      badgeColor: '#6b6b90', puffs: 'Device only',      price: '$15.00', specs: '1300mAh · USB-C · LED screen · Child lock',                                                       nicotine: 'Pods sold separately',         note: 'Compatible with all Prism pods',                                           flavours: [] },
      { name: 'Inmood 10K — Starter Kit',                   badge: 'STARTER KIT', badgeColor: '#FF2079', puffs: '10,000 puffs',     price: '$25.00', specs: '15ml · 1.0Ω coil · PG:VG 55:45',                                                                  nicotine: '26mg/ml (4% Nic Salt)',        note: 'All flavours come with an icy cool finish · Includes battery + pod',       flavours: ['Pineapple','Kiwifruit Pineapple','Mango Peach','Peach Apple','Cherry Pomegranate','Raspberry Grape','Blueberry Raspberry','Strawberry Kiwifruit','Banana Mango','Pear Lime','Cherry Berry','Strawberry Blueberry','Vanilla Spice','Grape Peach','Apple Grape','Strawberry Raspberry','Watermelon Blackberry','Blueberry Pomegranate','Sour Apple','Caramel Custard','Blueberry','Tobacco','Sour Mango','Sour Lemon','Strawberry Watermelon','Mint','Menthol','Grape Berry'] },
      { name: 'Inmood 10K — Replacement Pods',              badge: 'POD',         badgeColor: '#FF2079', puffs: '10,000 puffs',     price: '$20.00', specs: '15ml · Requires Inmood 10K battery device',                                                       nicotine: '26mg/ml (4% Nic Salt)',        note: 'All flavours come with an icy cool finish',                                flavours: ['Pineapple','Kiwifruit Pineapple','Mango Peach','Peach Apple','Cherry Pomegranate','Raspberry Grape','Blueberry Raspberry','Strawberry Kiwifruit','Banana Mango','Pear Lime','Cherry Berry','Strawberry Blueberry','Vanilla Spice','Grape Peach','Apple Grape','Strawberry Raspberry','Watermelon Blackberry','Blueberry Pomegranate','Sour Apple','Caramel Custard','Blueberry','Tobacco','Sour Mango','Sour Lemon','Strawberry Watermelon','Mint','Menthol','Grape Berry'] },
      { name: 'Inmood Prism — Replacement Pods 15K (10mg)', badge: 'POD',         badgeColor: '#FF2079', puffs: '15,000 puffs',     price: '$20.00', specs: '16ml · Dual mesh coils · Requires Prism Battery Kit',                                            nicotine: '10mg/mL (Low Strength)',       note: 'Requires Inmood Prism Battery Kit (sold separately)',                      flavours: ['Cherry Blueberry','Strawberry Blueberry','Pineapple Coconut','Blueberry Raspberry','Sour Apple','Strawberry Watermelon','Mango Grape','Cherry Pomegranate'] },
    ],
  },
  {
    name: 'FREEBASE E-LIQUID', color: '#f59e0b',
    products: [
      { name: 'Slapple 3mg 120ml — Ice Edition',  badge: 'FREEBASE', badgeColor: '#f59e0b', puffs: '120ml', price: '$35.00', specs: '3mg freebase · 120ml · Icy finish on all flavours · Sub-ohm ready',  nicotine: '3mg/ml Freebase', note: 'All flavours have an icy finish', flavours: ['Apple Pear','Blackberry Lemon','Blueberry Raspberry','Kiwifruit Pineapple','Lychee Peach','Mango Passionfruit','Menthol','Orange Guava','Pineapple Lemon','Sour Lemon','Spear Mint','Strawberry Watermelon','Tropical Berry'] },
      { name: 'Slapple 3mg 120ml — Zero Ice',     badge: 'FREEBASE', badgeColor: '#f59e0b', puffs: '120ml', price: '$35.00', specs: '3mg freebase · 120ml · No icy finish · Sub-ohm ready',              nicotine: '3mg/ml Freebase', note: 'Smooth flavour — no ice finish',   flavours: ['Banana','Berries','Blueberry Raspberry','Caramel Custard','Caramel Tobacco','Grape','Peach Pineapple','Strawberry Guava'] },
      { name: 'Cloudys E-Liquid 100ml 3mg',       badge: 'FREEBASE', badgeColor: '#f59e0b', puffs: '100ml', price: '$35.00', specs: '3mg freebase · 100ml · Best value size · Sub-ohm ready',            nicotine: '3mg/ml Freebase', note: 'Best value — great for sub-ohm devices', flavours: ['Banana Berry','Blueberry Menthol','Blueberry Raspberry','Grape','Lemon Lime','Mango','Mint','Passionfruit Lychee','Peach','Peach Apple','Sour Apple','Sour Berry','Strawberry','Sweet Pineapple','Vanilla Spice','Watermelon'] },
      { name: 'NZ Vapor E-Liquid Freebase 0MG 60ml',          badge: 'FREEBASE', badgeColor: '#f59e0b', puffs: '60ml',  price: '$30.00', specs: '0mg nicotine · 60ml freebase · Nicotine free · Sub-ohm ready',    nicotine: '0mg — Nicotine Free', note: 'Zero nicotine freebase',          flavours: ['Blackberry','Mango Mango','Strawberry'] },
      { name: 'NZ Vapor E-Liquid Freebase 10MG 60ml',         badge: 'FREEBASE', badgeColor: '#f59e0b', puffs: '60ml',  price: '$30.00', specs: '10mg freebase · 60ml · Sub-ohm ready · Wide flavour range',       nicotine: '10mg/ml Freebase',    note: 'Medium strength freebase',        flavours: ['Banana Caramel','Blackberry','ESP-Resso','Kiwifruit Watermelon','Mango Mango','Menthol','Menthol Tobacco','Peach Passionfruit','Raspberry Pineapple','Strawberry','Sweet Pineapple','Tobacco (Red)','Tobacco (Gold)','Tobacco Latte','Tobacco Vanilla','Tobacco Silver','Tobacco (Purple)','Tobacco (Blue)','Tropical','Watermelon Peach'] },
      { name: 'NZ Vapor E-Liquid Freebase 15MG 60ml',         badge: 'FREEBASE', badgeColor: '#f59e0b', puffs: '60ml',  price: '$30.00', specs: '15mg freebase · 60ml · Sub-ohm ready · Wide flavour range',       nicotine: '15mg/ml Freebase',    note: 'Higher strength freebase',        flavours: ['Banana Caramel','Blackberry','ESP-Resso','Kiwifruit Watermelon','Mango Mango','Menthol','Menthol Tobacco','Peach Passionfruit','Raspberry Pineapple','Sweet Pineapple','Tobacco Blue','Tobacco Latte','Tobacco Red','Tobacco Vanilla','Tobacco Silver','Tobacco (Gold)','Tobacco (Purple)','Tropical','Watermelon Peach'] },
    ],
  },
  {
    name: 'VAPURE NIC SALT', color: '#00e5ff',
    products: [
      { name: 'Slapple E-Liquid 20mg 30ml',       badge: 'NIC SALT', badgeColor: '#00e5ff', puffs: '30ml', price: '$25.00', specs: '20mg nicotine salt · 30ml · Made for pod systems', nicotine: '20mg/ml Nic Salt', note: 'Mix of Ice & Zero Ice flavours', flavours: ['Banana (Zero Ice)','Berries (Zero Ice)','Blackberry Lemon','Blueberry Raspberry','Blueberry Raspberry (Zero Ice)','Caramel Custard','Caramel Tobacco (Zero Ice)','Kiwifruit Pineapple','Lychee Peach','Peach Pineapple (Zero Ice)','Pineapple Lemon','Sour Lemon','Strawberry Watermelon','Strawberry Guava (Zero Ice)','Tropical Berry'] },
      { name: 'Slapple E-Liquid 10mg 30ml',       badge: 'NIC SALT', badgeColor: '#00e5ff', puffs: '30ml', price: '$25.00', specs: '10mg nicotine salt · 30ml · Lower strength · Made for pod systems', nicotine: '10mg/ml Nic Salt', note: 'Mix of Ice & Zero Ice flavours', flavours: ['Banana (Zero Ice)','Berries (Zero Ice)','Blackberry Lemon','Blueberry Raspberry','Blueberry Raspberry (Zero Ice)','Caramel Custard','Caramel Tobacco (Zero Ice)','Kiwifruit Pineapple','Lychee Peach','Peach Pineapple (Zero Ice)','Pineapple Lemon','Sour Lemon','Strawberry Watermelon','Strawberry Guava (Zero Ice)','Tropical Berry'] },
      { name: 'Cloudys E-Liquid 30ml Nic Salt',   badge: 'NIC SALT', badgeColor: '#00e5ff', puffs: '30ml', price: '$25.00', specs: '30ml · Nic Salt · Pod systems & low wattage devices', nicotine: 'Available in 3 strengths', note: 'Choose your nicotine strength below', flavours: ['Banana Berry','Blueberry Menthol','Blueberry Raspberry','Grape','Lemon Lime','Mango','Menthol','Mint','Nut Tobacco','Passionfruit Lychee','Peach','Peach Apple','Sour Apple','Sour Berry','Strawberry','Tobacco','Vanilla Spice','Watermelon'],
        variants: [
          { strength: '11mg', nicSalt: '20mg Nic Salt', note: 'Smooth — ideal for new vapers', color: '#4ade80' },
          { strength: '20mg', nicSalt: '35mg Nic Salt', note: 'Medium — most popular choice',  color: '#f472b6' },
          { strength: '28mg', nicSalt: '50mg Nic Salt', note: 'High — for heavy smokers',      color: '#f87171' },
        ]
      },
      { name: 'Cloudys Premium E-Liquid 30ml',    badge: 'NIC SALT', badgeColor: '#f472b6', puffs: '30ml', price: '$25.00', specs: '30ml · Premium Nic Salt · Pod systems & low wattage devices', nicotine: 'Available in 3 strengths', note: 'Choose your nicotine strength below', flavours: ['Banana Berry','Blueberry Menthol','Blueberry Raspberry','Grape','Lemon Lime','Mango','Menthol','Mint','Nut Tobacco','Passionfruit Lychee','Peach','Peach Apple','Sour Apple','Sour Berry','Strawberry','Tobacco','Vanilla Spice','Watermelon'],
        variants: [
          { strength: '11mg', nicSalt: '20mg Nic Salt', note: 'Smooth — ideal for new vapers', color: '#4ade80' },
          { strength: '20mg', nicSalt: '35mg Nic Salt', note: 'Medium — most popular choice',  color: '#f472b6' },
          { strength: '28mg', nicSalt: '50mg Nic Salt', note: 'High — for heavy smokers',      color: '#f87171' },
        ]
      },
      { name: 'Vapure Nic Salt by NZVapor 30ml',  badge: 'NIC SALT', badgeColor: '#00e5ff', puffs: '30ml', price: '$10.00', specs: 'Nic salt · 30ml · Pod systems · NZ made', nicotine: 'Nic Salt', note: 'Locally made NZ brand', flavours: ['Fizz Berry','Grape Ice','Premium Blue','Aloe Pear','Arctic Ice','Blackcurrant Ice','Peach Ice','Perfectly Mint','Premium Gold','Premium Red','Premium Silver','Razz Ripple','Royale Vape','Stoney Fruits','Strawberry'] },
    ],
  },
  {
    name: 'SOLO', color: '#ef4444',
    products: [
      { name: 'SOLO Ultra Kit 12K',               badge: 'STARTER KIT', badgeColor: '#ef4444', puffs: '12,000 puffs', price: '$30.00', specs: 'Ultra device · 12,000 puffs · Rechargeable · USB-C · Includes battery + pod', nicotine: '20mg/ml', note: 'Includes battery + pod', flavours: ['Blueberry Raspberry','Cherry Pomegranate','Cherry Sweet','Sour Apple','Sour Grape','Tropical Passionfruit'] },
      { name: 'SOLO Ultra Pod 12K',               badge: 'POD',         badgeColor: '#ef4444', puffs: '12,000 puffs', price: '$20.00', specs: 'Ultra replacement pod · 12,000 puffs · Requires SOLO Ultra Device', nicotine: '20mg/ml', note: 'Requires SOLO Ultra Device (sold separately)', flavours: ['Blueberry Raspberry','Cherry Pomegranate','Cherry Sweet','Kiwifruit Pineapple','Lemon Lime','Lemon Tea','Raspberry Lime','Sour Apple','Sour Grape','Strawberry Watermelon','Sweet Banana','Sweet Lychee','Sweet Peach'] },
      { name: 'SOLO Ultra Device',                badge: 'DEVICE',      badgeColor: '#6b6b90', puffs: 'Device only',  price: '$15.00', specs: 'SOLO Ultra battery device · USB-C · Compatible with SOLO Ultra pods', nicotine: 'Pods sold separately', note: 'Black only', flavours: [] },
      { name: 'SOLO Plus Pods',                   badge: 'POD',         badgeColor: '#ef4444', puffs: '—',           price: '$20.00', specs: 'SOLO Plus replacement pods · Compatible with SOLO Plus device', nicotine: '20mg/ml', note: 'Pod only', flavours: ['Banana','Blueberry Raspberry','Grape Mint','Menthol','Mint','Passionfruit','Peach Mint','Peppermint','Sour Apple','Sour Lime','Sour Raspberry','Spearmint','Strawberry Mint','Tobacco','Watermelon Mint'] },
    ],
  },
  {
    name: 'ALT', color: '#818cf8',
    products: [
      { name: 'Alt Single Pods',                  badge: 'POD',         badgeColor: '#818cf8', puffs: '—',   price: '$10.00', specs: 'Alt single replacement pod · For Alt POD device', nicotine: '20mg/ml', note: 'Compatible with Alt POD device', flavours: ['Aqua Mint','Gold Tobacco','Grape Mint','Mango Ice','Menthol Ice','Peach Ice','Pineapple','Strawberry Ice'] },
      { name: 'Alt. Replacement Pods 2%',         badge: 'POD',         badgeColor: '#818cf8', puffs: '—',   price: '$19.99', specs: 'Alt 2% replacement pods · 2-pack', nicotine: '2% (20mg/ml)', note: 'Pod 2-pack', flavours: ['Menthol','Mint','Sweet Tobacco','Tobacco'] },
      { name: 'Alt. Replacement Pods 2.85%',      badge: 'POD',         badgeColor: '#818cf8', puffs: '—',   price: '$19.99', specs: 'Alt 2.85% replacement pods · 2-pack', nicotine: '2.85% (28.5mg/ml)', note: 'Mid strength pods', flavours: ['Menthol','Menthol Spearmint','Mint','Peppermint','Spearmint'] },
      { name: 'Alt. Nu Pods 2%',                  badge: 'POD',         badgeColor: '#818cf8', puffs: '—',   price: '$19.99', specs: 'Alt Nu pods · 2% strength · Wide flavour range', nicotine: '2% (20mg/ml)', note: 'Nu range pods', flavours: ['Apple','Blackberry Mint','Cream Mint','Grape Mint','Guava Kiwifruit','Kiwifruit Strawberry','Lemon','Menthol Mint','Orange','Peach Mint','Pineapple Mint','Spearmint Mint','Strawberry Lemon','Strawberry Mint','Strawberry Watermelon','Sweet Mango','Sweet Menthol','Sweet Tobacco','Sweet Vanilla'] },
      { name: 'Alt. Nu Pods 2.85%',               badge: 'POD',         badgeColor: '#818cf8', puffs: '—',   price: '$19.99', specs: 'Alt Nu pods · 2.85% strength · Wide flavour range', nicotine: '2.85% (28.5mg/ml)', note: 'Mid strength Nu range pods', flavours: ['Apple','Blackberry Mint','Cream Mint','Grape Mint','Guava Kiwifruit','Kiwifruit Strawberry','Lemon','Menthol Mint','Orange','Peach Mint','Pineapple Mint','Spearmint Mint','Strawberry Lemon','Strawberry Mint','Strawberry Watermelon','Sweet Mango','Sweet Menthol','Sweet Tobacco','Sweet Vanilla'] },
      { name: 'Alt.X Pods',                       badge: 'POD',         badgeColor: '#818cf8', puffs: '—',   price: '$20.00', specs: 'Alt.X replacement pods · For Alt.X device', nicotine: '20mg/ml', note: 'Compatible with Alt.X device', flavours: ['Apple','Blackberry','Grape','Guava Kiwifruit','Kiwifruit Strawberry','Menthol','Mint (Chill)','Mint (Spring)','Peach','Pineapple','Strawberry','Strawberry Lemon','Strawberry Watermelon','Tobacco'] },
      { name: 'Alt.X Device',                     badge: 'DEVICE',      badgeColor: '#6b6b90', puffs: 'Device only', price: '$15.00', specs: 'Alt.X battery device · USB-C · Compatible with Alt.X pods', nicotine: 'Pods sold separately', note: 'Black only', flavours: [] },
      { name: 'Alt Battery',                      badge: 'DEVICE',      badgeColor: '#6b6b90', puffs: 'Device only', price: '$14.99', specs: 'Alt battery device · Compatible with Alt single pods', nicotine: 'Pods sold separately', note: 'Available in Aurora, Black, Comet, Midnight', flavours: [] },
    ],
  },
  {
    name: 'BUD', color: '#a3e635',
    products: [
      { name: 'Bud 2.8% Pod Kit',         badge: 'STARTER KIT', badgeColor: '#a3e635', puffs: '—', price: '$25.00', specs: '2.8% nicotine · Pod kit · Rechargeable · Includes battery + pod', nicotine: '2.8% (28mg/ml)', note: 'Includes battery + pod', flavours: ['Blueberry Raspberry','Cherry Pomegranate','Grape Mint','Mint','Strawberry Kiwifruit','Watermelon Mint'] },
      { name: 'Bud Pods 2.8% — Pack of 2', badge: 'POD',         badgeColor: '#a3e635', puffs: '—', price: '$24.99', specs: '2.8% nicotine · Pack of 2 pods · Replacement pods for Bud device', nicotine: '2.8% (28mg/ml)', note: 'Pack of 2 pods — battery sold separately', flavours: ['Banana','Blueberry Raspberry','Cherry Pomegranate','Citrus','Grape Mint','Lemon Lime','Mango','Mango Watermelon','Mint','Passionfruit Sour','Peppermint','Sour Apple','Sour Lychee','Sour Orange','Sour Pineapple','Spearmint','Strawberry Kiwifruit','Strawberry Passionfruit','Strawberry Watermelon','Sweet Ice','Tobacco','Watermelon Mint'] },
      { name: 'Bud Battery',               badge: 'DEVICE',      badgeColor: '#6b6b90', puffs: 'Device only', price: '$14.99', specs: 'Bud battery device · Compatible with Bud pods', nicotine: 'Pods sold separately', note: 'Cream colour only', flavours: [] },
    ],
  },
  {
    name: 'GRABIT', color: '#f97316',
    products: [
      { name: 'Grabit Nex+ Starter Kit',        badge: 'STARTER KIT', badgeColor: '#f97316', puffs: '—',           price: '$10.00', specs: 'Rechargeable · USB-C · Refillable pod system · Includes battery + pod', nicotine: '20mg/ml', note: 'Includes battery + pod', flavours: ['Banana','Blueberry Raspberry','Cherry Pomegranate','Mango','Mango Pineapple','Menthol','Mint','Passionfruit Guava','Peach Pineapple','Pineapple Kiwifruit','Plum','Sour Apple','Sour Grape','Sour Lemon','Sour Raspberry','Spearmint','Strawberry Kiwifruit','Strawberry Passionfruit','Strawberry Watermelon','Tobacco','Vanilla Spice','Watermelon Mint'] },
      { name: 'Grabit Nex+ Replacement Pods',   badge: 'POD',         badgeColor: '#f97316', puffs: '—',           price: '$10.00', specs: 'Fits Grabit Nex+ battery kit · Replacement pod', nicotine: '20mg/ml', note: 'Pod only — battery sold separately', flavours: ['Banana','Blueberry Raspberry','Cherry Pomegranate','Mango','Mango Pineapple','Menthol','Mint','Passionfruit Guava','Peach Pineapple','Pineapple Kiwifruit','Plum','Sour Apple','Sour Grape','Sour Lemon','Sour Raspberry','Spearmint','Strawberry Kiwifruit','Strawberry Passionfruit','Strawberry Watermelon','Tobacco','Vanilla Spice','Watermelon Mint'] },
      { name: 'Grabit Unique 26K Puffs Pod',    badge: 'POD',         badgeColor: '#f97316', puffs: '26,000 puffs', price: '$20.00', specs: '26,000 puffs · Pre-filled pod · Rechargeable',    nicotine: '20mg/ml', note: 'Long-lasting pod system',            flavours: ['Blackberry Apple','Blackberry Licorice','Blueberry Cherry','Blueberry Raspberry','Cherry Pomegranate','Grape Berry','Grape Peach','Mango Tropical','Pineapple Kiwifruit','Pineapple Coconut','Strawberry Cream','Strawberry Pear'] },
    ],
  },
  {
    name: 'IGET', color: '#38bdf8',
    products: [
      { name: 'IGET Bar 3500 Puffs Disposable',   badge: 'DISPOSABLE',  badgeColor: '#38bdf8', puffs: '3,500 puffs',  price: '$28.00', specs: '2% nicotine · Pre-filled disposable · No charging required', nicotine: '2% (20mg/ml)', note: 'Single use disposable — ready to use', flavours: ['Apple','Banana','Blackberry','Blueberry','Blueberry Raspberry','Cherry Blueberry','Cherry Pomegranate','Grape','Kiwifruit Pineapple','Mango','Mint','Passionfruit Watermelon','Peach','Raspberry Grape','Strawberry Lemon','Strawberry Raspberry','Strawberry Watermelon','Strawberry Kiwifruit','Watermelon','Watermelon Mint'] },
      { name: 'IGET Moon Disposable 5000 Puffs',  badge: 'DISPOSABLE',  badgeColor: '#38bdf8', puffs: '5,000 puffs',  price: '$30.00', specs: '2% nicotine · Pre-filled disposable · No charging required', nicotine: '2% (20mg/ml)', note: 'Single use disposable — ready to use', flavours: ['Banana','Blackberry','Blueberry Raspberry','Cherry Blueberry','Cherry Pear','Grape','Mango','Mint','Passionfruit Lychee','Peach','Peach Apple','Pineapple Coconut','Pineapple Kiwifruit','Pomegranate Kiwifruit','Raspberry Grape','Sour Apple','Strawberry Kiwifruit','Strawberry Raspberry','Strawberry Watermelon','Tobacco','Watermelon'] },
      { name: 'IGET 5000 Puffs Disposable',       badge: 'DISPOSABLE',  badgeColor: '#38bdf8', puffs: '5,000 puffs',  price: '$35.00', specs: '2% nicotine · Pre-filled disposable · Ice flavours', nicotine: '2% (20mg/ml)', note: 'All ice flavours for extra cool hit', flavours: ['Banana Ice','Blueberry Raspberry Ice','Double Apple','Dragon Fruit Lemon Ice','Grape Ice','Melon Pineapple Orange','Passionfruit Kiwi Guava Ice','Passionfruit Lychee','Peach Apple Ice','Pineapple Kiwi Ice','Pomegranate Kiwi Ice','Strawberry Kiwi Ice','Strawberry Orange Green Ice','Strawberry Watermelon Ice','Watermelon Apple','Watermelon Ice'] },
      { name: 'IGET Stick Disposable',            badge: 'DISPOSABLE',  badgeColor: '#38bdf8', puffs: '—',           price: '$35.00', specs: '2% nicotine · Slim stick design · Pre-filled disposable', nicotine: '2% (20mg/ml)', note: 'Slim & discreet design', flavours: ['Aloe Mango','Aloe Mango Cantaloupe','Blackberry Ice','Blue Razz','Blueberry','Blueberry Raspberry Grape Ice','Cola Ice','Grape Ice','Lush Ice','Mango Banana','Orange Melon','Passion Fruit Mango Ice','Passion Fruit Melon Ice','Passionfruit','Peach Guava','Peach Pineapple','Peach Strawberry Ice','Pineapple Watermelon','Pink Lemon Orange','Raspberry Watermelon','Strawberry Kiwi','Strawberry Watermelon','Watermelon Kiwi','Watermelon Kiwi Pomegranate'] },
      { name: 'IGET 6000 Starter Kit',            badge: 'STARTER KIT', badgeColor: '#38bdf8', puffs: '6,000 puffs',  price: '$30.00', specs: 'Rechargeable · USB-C · Pre-filled pod · 6,000 puffs', nicotine: '20mg/ml', note: 'Includes battery + pod', flavours: ['Apple','Apple Grape','Apple Grape Ice','Banana','Banana Ice','Banana Pineapple','Blackberry','Blueberry','Blueberry Raspberry','Cherry Pomegranate','Cola Ice','Double Apple','Grape','Grape Peach','Grape Peach Ice','Grape Ice','Kiwi Pineapple Ice','Lychee Watermelon','Mango','Melon Ice','Mint','Orange Grapefruit Lemon','Orange Lemon','Passionfruit Kiwi Guava','Pineapple Banana','Pineapple Kiwifruit','Raspberry Berry','Strawberry Kiwi Ice','Strawberry Kiwifruit','Strawberry Raspberry','Strawberry Watermelon','Tobacco','Watermelon','Watermelon Ice','Watermelon Mint','Watermelon Mint Ice'] },
      { name: 'IGET 6000 Replacement Pods',       badge: 'POD',         badgeColor: '#38bdf8', puffs: '6,000 puffs',  price: '$15.00', specs: 'Fits IGET 6000 battery device · Pre-filled replacement pod', nicotine: '20mg/ml', note: 'Pod only — battery sold separately', flavours: ['Apple','Apple Grape','Apple Grape Ice','Banana','Banana Ice','Banana Pineapple','Blackberry','Blueberry','Blueberry Raspberry','Cherry Pomegranate','Cola Ice','Double Apple','Grape','Grape Peach','Grape Peach Ice','Grape Ice','Kiwi Pineapple Ice','Lychee Watermelon','Mango','Melon Ice','Mint','Orange Grapefruit Lemon','Orange Lemon','Passionfruit Kiwi Guava','Pineapple Banana','Pineapple Kiwifruit','Raspberry Berry','Strawberry Kiwi Ice','Strawberry Kiwifruit','Strawberry Raspberry','Strawberry Watermelon','Tobacco','Watermelon','Watermelon Ice','Watermelon Mint','Watermelon Mint Ice'] },
      { name: 'IGET Bar Plus 2.0 Kit 6000',       badge: 'STARTER KIT', badgeColor: '#38bdf8', puffs: '6,000 puffs',  price: '$30.00', specs: 'Bar Plus 2.0 · Rechargeable · USB-C · Includes battery + pod', nicotine: '20mg/ml', note: 'Includes battery + pod', flavours: ['Apple','Apple Grape','Banana','Blackberry','Blueberry','Grape','Grape Peach','Mango','Mint','Orange Lemon','Pineapple Banana','Pineapple Kiwifruit','Strawberry Kiwifruit','Strawberry Raspberry','Strawberry Watermelon','Tobacco','Watermelon','Watermelon Mint'] },
      { name: 'IGET Bar Plus Battery',            badge: 'DEVICE',      badgeColor: '#6b6b90', puffs: 'Device only',  price: '$15.00', specs: 'Bar Plus battery device · USB-C · Compatible with Bar Plus pods', nicotine: 'Pods sold separately', note: 'Compatible with all Bar Plus pods', flavours: [] },
      { name: 'IGET Bar Plus 3.0 Battery',        badge: 'DEVICE',      badgeColor: '#6b6b90', puffs: 'Device only',  price: '$15.00', specs: 'Bar Plus 3.0 battery device · USB-C · Upgraded device', nicotine: 'Pods sold separately', note: 'Compatible with Bar Plus 3.0 pods', flavours: [] },
      { name: 'IGET V3 Kit',                      badge: 'STARTER KIT', badgeColor: '#38bdf8', puffs: '10,000 puffs', price: '$30.00', specs: 'V3 pod system · Rechargeable · USB-C · Includes battery + pod', nicotine: '20mg/ml', note: 'Includes battery + pod', flavours: ['Blueberry Peach','Blueberry Cherry','Cherry Blackberry','Cherry Pomegranate','Grape Berry','Mango Guava','Pineapple Kiwifruit','Pomegranate Kiwifruit','Raspberry Lime','Strawberry Lychee','Watermelon Passionfruit','Lemon Pineapple'] },
      { name: 'IGET V4 Battery Kit',              badge: 'DEVICE',      badgeColor: '#6b6b90', puffs: 'Device only',  price: '$15.00', specs: 'V4 battery device · USB-C · Latest IGET device', nicotine: 'Pods sold separately', note: 'Compatible with V4 pods', flavours: [] },
      { name: 'IGET 10000 Puffs Pod',             badge: 'POD',         badgeColor: '#38bdf8', puffs: '10,000 puffs', price: '$20.00', specs: 'Pre-filled pod · 10,000 puffs · Rechargeable', nicotine: '20mg/ml', note: 'Pod only — requires compatible battery', flavours: ['Apple Banana','Blueberry Cherry','Blueberry Kiwifruit','Blueberry Peach','Caramel Lemon','Cherry Blackberry','Cherry Pomegranate','Grape Berry','Grape Menthol','Grape Pomegranate','Lemon Pineapple','Mango Guava','Peach Lychee','Pineapple Kiwifruit','Pineapple Passionfruit','Pomegranate Kiwifruit','Raspberry Lime','Strawberry Lychee','Strawberry Raspberry','Watermelon Passionfruit'] },
      { name: 'IGET Luna Kit 13K',                badge: 'STARTER KIT', badgeColor: '#38bdf8', puffs: '13,000 puffs', price: '$35.00', specs: 'Luna device · 13,000 puffs · Rechargeable · USB-C · Includes battery + pod', nicotine: '20mg/ml', note: 'Includes battery + pod', flavours: ['Apple','Banana','Blackberry','Blackberry Pomegranate','Blueberry Raspberry','Caramel Lemon','Cherry Lime','Citrus Berry','Grape','Grape Berry','Lemon','Mango','Mango Tropical','Mint','Orange','Passionfruit Lychee','Peach Apple','Peach Pineapple','Pineapple Coconut','Pineapple Kiwifruit','Pomegranate Kiwifruit','Strawberry Cream','Strawberry Kiwifruit','Strawberry Raspberry','Strawberry Watermelon','Sweet Grape','Vanilla Custard','Watermelon','Watermelon Pineapple'] },
      { name: 'IGET Luna Pod 13K',                badge: 'POD',         badgeColor: '#38bdf8', puffs: '13,000 puffs', price: '$20.00', specs: 'Luna pre-filled pod · 13,000 puffs · Requires Luna Battery Kit', nicotine: '20mg/ml', note: 'Requires Luna Battery Kit (sold separately)', flavours: ['Apple','Banana','Blackberry','Blackberry Pomegranate','Blueberry Raspberry','Caramel Lemon','Cherry Lime','Citrus Berry','Grape','Grape Berry','Lemon','Mango','Mango Tropical','Mint','Orange','Passionfruit Lychee','Peach Apple','Peach Pineapple','Pineapple Coconut','Pineapple Kiwifruit','Pomegranate Kiwifruit','Strawberry Cream','Strawberry Kiwifruit','Strawberry Raspberry','Strawberry Watermelon','Sweet Grape','Vanilla Custard','Watermelon','Watermelon Pineapple'] },
      { name: 'IGET Luna Battery Kit',            badge: 'DEVICE',      badgeColor: '#6b6b90', puffs: 'Device only',  price: '$15.00', specs: 'Luna battery device · USB-C · Compatible with Luna pods', nicotine: 'Pods sold separately', note: 'Compatible with all Luna pods', flavours: [] },
      { name: 'IGET Edge Kit',                    badge: 'STARTER KIT', badgeColor: '#38bdf8', puffs: '—',           price: '$30.00', specs: 'Edge pod system · Rechargeable · USB-C · Includes battery + pod', nicotine: '20mg/ml', note: 'Includes battery + pod', flavours: ['Apple Kiwifruit','Blackberry Cherry','Blackberry Pear','Blueberry Raspberry','Cherry Pomegranate','Grape Berry','Grape Peach','Kiwifruit Guava','Kiwifruit Pineapple','Lemon Passionfruit','Lime Mango','Mint','Peach Mango','Peach Pineapple','Spearmint','Strawberry Kiwifruit','Strawberry Raspberry','Strawberry Watermelon','Tropical','Tropical Citrus'] },
      { name: 'IGET Edge Pods',                   badge: 'POD',         badgeColor: '#38bdf8', puffs: '—',           price: '$20.00', specs: 'Edge replacement pod · Fits Edge battery device', nicotine: '20mg/ml', note: 'Pod only — requires Edge battery', flavours: ['Apple Kiwifruit','Blackberry Cherry','Blackberry Pear','Blueberry Raspberry','Cherry Pomegranate','Grape Berry','Grape Peach','Kiwifruit Guava','Kiwifruit Pineapple','Lemon Passionfruit','Lime Mango','Mint','Peach Mango','Peach Pineapple','Spearmint','Strawberry Kiwifruit','Strawberry Raspberry','Strawberry Watermelon','Tobacco','Tropical','Tropical Citrus'] },
      { name: 'IGET Edge 15K Kit',                badge: 'STARTER KIT', badgeColor: '#38bdf8', puffs: '15,000 puffs', price: '$35.00', specs: 'Edge 15K · Rechargeable · USB-C · 15,000 puffs · Includes battery + pod', nicotine: '20mg/ml', note: 'Includes battery + pod', flavours: ['Apple Kiwifruit','Blackberry Cherry','Blackberry Pear','Blackberry Berry','Blueberry Cherry','Blueberry Raspberry','Cherry Pomegranate','Grape Berry','Grape Peach','Kiwifruit Guava','Kiwifruit Pineapple','Lemon Passionfruit','Lime Mango','Mango Banana','Mint','Orange Kiwifruit','Passionfruit Pomegranate','Peach Mango','Peach Pineapple','Pineapple Berry','Spearmint','Strawberry Kiwifruit','Strawberry Pineapple','Strawberry Raspberry','Strawberry Watermelon','Sweet Grape','Tobacco','Tropical','Tropical Citrus'] },
      { name: 'IGET Edge 15K Pods',               badge: 'POD',         badgeColor: '#38bdf8', puffs: '15,000 puffs', price: '$25.00', specs: 'Edge 15K replacement pod · Requires Edge battery device', nicotine: '20mg/ml', note: 'Pod only — requires Edge battery device', flavours: ['Apple Kiwifruit','Blackberry Cherry','Blackberry Pear','Blackberry Berry','Blueberry Cherry','Blueberry Raspberry','Cherry Pomegranate','Grape Berry','Grape Peach','Kiwifruit Guava','Kiwifruit Pineapple','Lemon Passionfruit','Lime Mango','Mango Banana','Mint','Orange Kiwifruit','Passionfruit Pomegranate','Peach Mango','Peach Pineapple','Pineapple Berry','Spearmint','Strawberry Kiwifruit','Strawberry Pineapple','Strawberry Raspberry','Strawberry Watermelon','Sweet Grape','Tobacco','Tropical','Tropical Citrus'] },
      { name: 'IGET Edge Battery',                badge: 'DEVICE',      badgeColor: '#6b6b90', puffs: 'Device only',  price: '$15.00', specs: 'Edge battery device · USB-C · Compatible with Edge pods', nicotine: 'Pods sold separately', note: 'Compatible with all Edge pods', flavours: [] },
      { name: 'IGET Bar Plus 4.0 Kit',            badge: 'STARTER KIT', badgeColor: '#38bdf8', puffs: '—',           price: '$35.00', specs: 'Bar Plus 4.0 · Latest generation · Rechargeable · USB-C · Includes battery + pod', nicotine: '20mg/ml', note: 'Includes battery + pod', flavours: ['Apple Cinnamon','Blackberry Grape','Blackberry Tropical','Blueberry Raspberry','Cherry Pomegranate','Grape Berry','Grape Kiwifruit','Guava Lime','Pineapple Kiwifruit','Pineapple Lemon','Strawberry Custard','Strawberry Kiwifruit','Watermelon Passionfruit'] },
      { name: 'IGET Bar Plus 4.0 Pods',           badge: 'POD',         badgeColor: '#38bdf8', puffs: '—',           price: '$25.00', specs: 'Bar Plus 4.0 replacement pod · Fits Bar Plus 4.0 Kit', nicotine: '20mg/ml', note: 'Pod only — requires Bar Plus 4.0 battery', flavours: ['Blackberry Grape','Blackberry Tropical','Blueberry Raspberry','Cherry Pomegranate','Grape Berry','Grape Kiwifruit','Guava Lime','Passionfruit Lychee','Peach Apple','Pineapple Coconut','Pineapple Kiwifruit','Pineapple Lemon','Raspberry Lemon','Strawberry Banana','Strawberry Custard','Strawberry Kiwifruit','Strawberry Watermelon'] },
      { name: 'IGET E-Liquid 28.5mg',             badge: 'E-LIQUID',    badgeColor: '#a78bfa', puffs: '—',           price: '$35.00', specs: 'Nic salt e-liquid · 28.5mg · Compatible with pod systems', nicotine: '28.5mg (Nic Salt)', note: 'High strength nic salt', flavours: ['Apple','Blueberry Raspberry','Cherry Pomegranate','Grape','Kiwifruit Passionfruit','Kiwifruit Pineapple','Lemon Pineapple','Mango','Pineapple Coconut','Raspberry Peach','Strawberry Peach','Strawberry Watermelon','Tropical'] },
    ],
  },
]


export type ProductVariant = { strength: string; nicSalt: string; note: string; color: string }
export type Product = typeof BRANDS[0]['products'][0] & { variants?: ProductVariant[] }

export function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
}

export function getAllProducts() {
  return BRANDS.flatMap(brand =>
    brand.products.map(product => ({
      ...product,
      brandName: brand.name,
      brandColor: brand.color,
      slug: slugify(product.name),
    }))
  )
}
